# configuaration class
:status:
  200: Successfully Processed
  204: No Content
  400: Bad Request
  403: Forbidden
  404: Image Not Found
  409: Conflict
  603: Action Unavailible
  601: Doesn't support this format
  602: Invalid Parameters
  603: Invalid Action

:content_type: application/json